{
 "title": "Lelit Mara X",
 "time": { "from": "now-30m", "to": "now-3m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature Eau",
   "type": "gauge",
   "description": "°C",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "select": [
      [
       { "params": [ "actual_hx_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "°C",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "select": [
      [
       { "params": [ "actual_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "En chauffe",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "measurement": "lelit",
     "query": "SELECT \"heating_element_state\" FROM \"lelit\"",
     "select": [
      [
       { "params": [ "heating_element_state" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT \"mode\" FROM \"lelit\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Fast heating",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "select": [
      [
       { "params": [ "countdown" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature Eau",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "query": "SELECT \"actual_hx_temp\" FROM \"lelit\" ",
     "select": [
      [
       { "params": [ "actual_hx_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vapeur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperature Vapeur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "query": "SELECT \"actual_temp\" FROM \"lelit\"",
     "select": [
      [
       { "params": [ "actual_temp" ], "type": "field" }
      ],
      [
       { "params": [ "actual_temp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "Target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "query": "SELECT \"target_temp\" FROM \"lelit\" ",
     "select": [
      [
       { "params": [ "target_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HX - Eau",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "query": "SELECT \"actual_hx_temp\" FROM \"lelit\" ",
     "select": [
      [
       { "params": [ "actual_hx_temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "lelit",
     "query": "SELECT \"actual_temp\" FROM \"lelit\" ",
     "select": [
      [
       { "params": [ "actual_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}